import 'dart:io';

import 'package:dsh_launcher/services/web_service.dart';
import 'package:flutter_test/flutter_test.dart';

/// 覆盖 dsh home 解析与孤儿写锁回收:
/// - DSH_HOME 优先于 ~/.dsh,支持 ~ 前缀;
/// - 仅删除「确实无持有者」的锁:空锁(且已过宽限)或死 PID 锁;
/// - 空锁过宽限期、活 PID 锁、非 atomic-write 锁(如 yarn.lock)、非 .lock 一律保留。
void main() {
  group('resolveDshHome', () {
    test('DSH_HOME 优先于 ~/.dsh', () {
      final home = WebService.resolveDshHome(
        env: {
          'DSH_HOME': r'E:\dsh-data',
          'USERPROFILE': r'C:\Users\me',
          'HOME': r'/home/me',
        },
      );
      expect(home, r'E:\dsh-data');
    });

    test('无 DSH_HOME 时默认 USERPROFILE/.dsh', () {
      final home = WebService.resolveDshHome(
        env: {'USERPROFILE': r'C:\Users\me'},
      );
      expect(home, r'C:\Users\me\.dsh');
    });

    test('空 DSH_HOME 视为未设置', () {
      final home = WebService.resolveDshHome(
        env: {'DSH_HOME': '   ', 'USERPROFILE': r'C:\Users\me'},
      );
      expect(home, r'C:\Users\me\.dsh');
    });

    test('HOME 回退(非 Windows)', () {
      final home = WebService.resolveDshHome(env: {'HOME': '/home/me'});
      expect(home, '/home/me${Platform.pathSeparator}.dsh');
    });

    test('DSH_HOME 的 ~ 前缀按 home 展开', () {
      final home = WebService.resolveDshHome(
        env: {'DSH_HOME': r'~\dsh-custom', 'USERPROFILE': r'C:\Users\me'},
      );
      expect(home, r'C:\Users\me\dsh-custom');
    });

    test('无任何 home 时返回 null', () {
      expect(WebService.resolveDshHome(env: {}), isNull);
    });
  });

  group('cleanStaleDshLocks', () {
    late Directory root;

    setUp(() {
      root = Directory.systemTemp.createTempSync('dsh_locks_test_');
    });

    tearDown(() {
      if (root.existsSync()) root.deleteSync(recursive: true);
    });

    File makeLock(String name, {String content = '', DateTime? modified}) {
      final f = File('${root.path}${Platform.pathSeparator}$name');
      f.writeAsStringSync(content);
      if (modified != null) {
        f.setLastModifiedSync(modified);
      }
      return f;
    }

    test('清理:过宽限期的空锁被删除', () async {
      final empty = makeLock(
        '.credentials.yaml.lock',
        modified: DateTime.now().subtract(const Duration(minutes: 1)),
      );
      final removed = await WebService.cleanStaleDshLocks(root);
      expect(removed, 1);
      expect(empty.existsSync(), isFalse);
    });

    test('保留:宽限期内的新空锁不被删除', () async {
      final fresh = makeLock('.credentials.yaml.lock');
      final removed = await WebService.cleanStaleDshLocks(
        root,
        emptyLockGrace: const Duration(minutes: 10),
      );
      expect(removed, 0);
      expect(fresh.existsSync(), isTrue);
    });

    test('清理:死 PID 锁被删除,活 PID 锁保留', () async {
      final dead = makeLock('settings.yaml.lock', content: '999999999\n');
      final alive = makeLock('.credentials.yaml.lock', content: '42\n');
      final removed = await WebService.cleanStaleDshLocks(
        root,
        pidAlive: (pid) async => pid == 42,
      );
      expect(removed, 1);
      expect(dead.existsSync(), isFalse);
      expect(alive.existsSync(), isTrue);
    });

    test('保留:非数字内容(如 yarn.lock)不被删除', () async {
      final yarn = makeLock(
        'yarn.lock',
        content: '# THIS IS AN AUTOGENERATED FILE\nlockfileVersion: 1\n',
      );
      final removed = await WebService.cleanStaleDshLocks(root);
      expect(removed, 0);
      expect(yarn.existsSync(), isTrue);
    });

    test('保留:非 .lock 文件不受影响', () async {
      final creds = makeLock('.credentials.yaml', content: 'key: value\n');
      final removed = await WebService.cleanStaleDshLocks(root);
      expect(removed, 0);
      expect(creds.existsSync(), isTrue);
    });

    test('只扫根目录:子目录内锁不处理', () async {
      final sub = Directory('${root.path}${Platform.pathSeparator}sub')
        ..createSync();
      final nested = File('${sub.path}${Platform.pathSeparator}deep.lock')
        ..writeAsStringSync('');
      final removed = await WebService.cleanStaleDshLocks(root);
      expect(removed, 0);
      expect(nested.existsSync(), isTrue);
    });
  });
}
